"""Contract knowledge base: how to classify a clause and what risk it carries.

Written from the contractor / supplier / service provider side of the
table, which is who this product serves: the question every rule answers
is "what does this clause cost us, and when?".

Party names vary by contract family (Company / Employer / Owner / Buyer /
Customer on one side; Contractor / Supplier / Vendor / Consultant /
Service Provider on the other), so patterns use {K} for the client side
and {C} for the contractor side, expanded at load time.

Adding coverage means adding a rule here. A rule has:
  triggers   - any of these in a sentence makes that sentence the evidence
  requires   - all of these must also appear (in the sentence, or clause
               when scope="clause")
  unless     - any of these anywhere in the clause suppresses the rule
               (a mitigant the drafting already provides)
  severity   - base severity
  bands      - numeric escalation from the figure in the evidence sentence
  escalate / mitigate - cues in the clause that move severity up or down
  context    - cues in *related* clauses that aggravate this one
"""

from dataclasses import dataclass, field

K = r"(?:company|client|employer|owner|purchaser|buyer|customer|principal|authority|operator|contracting entity)"
C = r"(?:contractor|supplier|vendor|consultant|service provider|seller|provider|subcontractor|manufacturer)"


def _x(patterns: tuple[str, ...]) -> tuple[str, ...]:
    return tuple(p.replace("{K}", K).replace("{C}", C) for p in patterns)


# ---------------------------------------------------------------------------
# Clause classification lexicon: subcategory -> (title cues, body cues)
# Title cues are strong evidence; body cues accumulate.
# ---------------------------------------------------------------------------

LEXICON: dict[str, tuple[tuple[str, ...], tuple[str, ...]]] = {
    # commercial
    "payment": ((r"payment", r"terms of payment", r"invoic.*payment", r"remuneration", r"fees?\b"),
                (r"\bpay\b", r"\bpaid\b", r"invoice", r"within \S+ \(?\d+\)? days", r"payable")),
    "retention": ((r"retention",), (r"\bretain\w*\b.*%", r"retention money", r"retained amount")),
    "advance_payment": ((r"advance payment", r"down ?payment", r"mobili[sz]ation payment"),
                        (r"advance payment", r"repaid by deduction", r"advance payment guarantee")),
    "price_adjustment": ((r"price adjustment", r"escalation", r"price review", r"indexation", r"rates? review"),
                         (r"firm and fixed", r"not be subject to adjustment", r"index", r"escalat", r"price review")),
    "currency": ((r"currenc", r"exchange rate"), (r"exchange rate", r"currency", r"denominated in")),
    "tax": ((r"tax", r"duties", r"vat", r"withholding"), (r"\btax(es)?\b", r"withholding", r"\bvat\b", r"duties", r"levies")),
    "set_off": ((r"set[- ]off", r"deduction", r"withholding of payment"), (r"set[- ]off", r"deduct .* from any (amount|sum)")),
    "reimbursement": ((r"reimburs", r"expenses", r"cost[- ]plus"), (r"reimburs", r"at cost", r"expenses", r"mark[- ]?up")),
    "invoicing": ((r"invoic",), (r"invoice shall", r"valid invoice", r"supporting documentation", r"field tickets")),
    "variations": ((r"variation", r"change order", r"change request", r"changes to the (works|services|scope)"),
                   (r"variation", r"change order", r"instruct(ed)? (a )?change", r"adjustment to the contract price")),
    "payment_security": ((r"letter of credit", r"payment security", r"payment guarantee", r"escrow"),
                         (r"letter of credit", r"payment guarantee", r"escrow")),
    "audit_rights": ((r"audit", r"records", r"books and accounts"), (r"\baudit\b", r"inspect .*records", r"books")),
    "pay_when_paid": ((r"pay when paid", r"pay if paid", r"back[- ]to[- ]back payment"),
                      (r"pay(?:ment)? when paid", r"pay if paid", r"(?:receipt|received) (?:of )?payment from the (?:owner|client|employer|end client)")),
    # schedule
    "milestones": ((r"milestone", r"completion date", r"programme", r"schedule of works", r"time for completion"),
                   (r"mechanical completion", r"milestone", r"shall (?:achieve|complete) .* by \d", r"completion date")),
    "delay": ((r"delay",), (r"\bdelay", r"late (?:delivery|completion)", r"behind (?:schedule|programme)")),
    "liquidated_damages": ((r"liquidated damages", r"delay damages", r"\blds?\b", r"penalt"),
                           (r"liquidated damages", r"delay damages", r"per day of delay", r"penalt(y|ies)")),
    "extension_of_time": ((r"extension of time", r"\beot\b", r"time extension"), (r"extension of time", r"extend the (?:time|completion date)")),
    "force_majeure": ((r"force majeure", r"exceptional event", r"act of god"), (r"force majeure", r"act of god", r"beyond (?:its|their) reasonable control")),
    "delivery": ((r"deliver(y|ies)", r"incoterms", r"shipment"), (r"deliver(ed|y)", r"incoterms", r"\b(?:ddp|dap|fca|exw|cif|fob)\b")),
    "suspension_of_works": ((r"suspension of (?:the )?works",), (r"suspend the works",)),
    # liability
    "liability_cap": ((r"limitation of liability", r"limit of liability", r"liability cap", r"cap on liability"),
                      (r"aggregate liability", r"shall not exceed", r"total liability", r"capped at", r"maximum liability")),
    "unlimited_liability": ((r"unlimited liability",), (r"without limit", r"unlimited", r"without regard to (?:the|any) limitation")),
    "indemnity": ((r"indemn", r"hold harmless", r"knock[- ]for[- ]knock"), (r"indemnif", r"hold harmless", r"defend")),
    "consequential_loss": ((r"consequential", r"indirect loss"), (r"consequential", r"indirect loss", r"loss of (?:profit|production|use)")),
    "third_party_claims": ((r"third[- ]party",), (r"third[- ]party (?:claims|injury|property)",)),
    "exclusive_remedies": ((r"exclusive remed", r"sole remed"), (r"sole and exclusive remedy", r"exclusive remed")),
    "limitation_period": ((r"limitation period", r"time for claims", r"claims period"),
                          (r"no claim may be (?:brought|made) after", r"limitation period", r"statute of limitation")),
    "environmental_liability": ((r"pollution", r"environment(?:al)? liabilit", r"contamination"),
                                (r"pollution", r"contamination", r"spill", r"environmental damage")),
    # performance
    "kpis": ((r"\bkpis?\b", r"key performance", r"performance indicators"), (r"\bkpi", r"key performance indicator")),
    "performance_guarantees": ((r"performance (?:guarantee|bond|security)", r"parent company guarantee", r"bank guarantee", r"security"),
                               (r"performance (?:guarantee|bond|security)", r"on[- ]demand", r"parent company guarantee", r"bank guarantee")),
    "acceptance": ((r"acceptance", r"taking over", r"commissioning", r"completion certificate", r"inspection and test"),
                   (r"acceptance", r"taking[- ]over", r"completion certificate", r"acceptance test")),
    "warranty": ((r"warrant", r"guarantee period"), (r"\bwarrants?\b", r"warranty period", r"months from (?:the date of )?(?:delivery|completion|acceptance)")),
    "defects": ((r"defect", r"remedial work"), (r"defect", r"re-?perform", r"remedy .* at (?:its|his) own cost")),
    "rework": ((r"re-?work", r"re-?performance"), (r"re-?perform", r"re-?work")),
    "fitness_for_purpose": ((r"fitness for purpose", r"fit for purpose"), (r"fit for (?:the|its) (?:intended )?purpose", r"fitness for purpose")),
    "design_responsibility": ((r"design",), (r"responsible for the design", r"design (?:responsibility|liability)", r"approval .* shall not relieve")),
    "service_levels": ((r"service levels?", r"\bslas?\b", r"availability", r"uptime", r"service credits?"),
                       (r"service level", r"service credit", r"availability of \d", r"uptime", r"response time")),
    "title_and_risk": ((r"title", r"risk of loss", r"passing of (?:title|risk)", r"ownership"),
                       (r"title (?:shall|to the \w+ shall) pass", r"risk (?:of loss )?shall pass", r"ownership")),
    # termination
    "termination_for_convenience": ((r"termination for convenience", r"terminat.*convenience"), (r"for (?:its|their) convenience", r"without cause")),
    "termination_for_cause": ((r"termination for (?:cause|default|breach)", r"default", r"terminat"),
                              (r"material breach", r"insolven", r"fails? to remedy", r"terminate .* (?:immediately|forthwith)")),
    "suspension": ((r"suspension", r"suspend"), (r"\bsuspend", r"suspension")),
    "demobilization": ((r"demobili[sz]",), (r"demobili[sz]",)),
    "step_in": ((r"step[- ]in",), (r"step[- ]in", r"take over (?:the )?(?:performance|works|services)")),
    "term_and_renewal": ((r"\bterm\b", r"duration", r"renewal", r"commencement and duration"),
                         (r"automatically renew", r"initial term", r"renewal term", r"extend the term")),
    # insurance
    "insurance_policy_requirements": ((r"insurance",), (r"insurance", r"insured", r"polic(?:y|ies)")),
    "insurance_limits": ((r"insurance (?:limits|cover)",), (r"insurance .* (?:limit|not less than)",)),
    "insurance_deductibles": ((r"deductible", r"excess"), (r"deductible", r"excess")),
    "additional_insured": ((r"additional insured", r"co-?insured"), (r"additional insured", r"co-?insured", r"waive .* subrogation")),
    # compliance
    "hse": ((r"health", r"safety", r"\bhse\b", r"\bhsse\b", r"environment"), (r"\bhse\b", r"safety", r"trir", r"ltif", r"incident")),
    "regulatory": ((r"compliance with laws?", r"applicable laws?", r"permits", r"regulat"), (r"applicable laws?", r"permits", r"licen[cs]es")),
    "sanctions": ((r"sanction", r"trade controls?"), (r"sanction",)),
    "anti_bribery": ((r"bribery", r"corruption", r"business ethics", r"improper payments"), (r"brib", r"corrupt", r"facilitation payment")),
    "local_content": ((r"local content", r"in[- ]country value", r"nationali[sz]ation", r"\bicv\b"), (r"local content", r"in-country")),
    "labor": ((r"labou?r", r"employment", r"personnel matters", r"immigration", r"visas?"), (r"work permits?", r"labou?r law", r"employees")),
    "data_protection": ((r"data protection", r"privacy", r"personal data", r"gdpr"), (r"personal data", r"data protection", r"gdpr", r"data subject")),
    "cyber_security": ((r"cyber", r"information security"), (r"cyber", r"information security", r"iso ?27001", r"security incident")),
    "export_control": ((r"export control", r"export licen"), (r"export control", r"re-?export", r"dual[- ]use")),
    # contractual
    "governing_law": ((r"governing law", r"applicable law", r"law of the contract"), (r"governed by (?:and construed in accordance with )?the laws? of",)),
    "jurisdiction": ((r"jurisdiction",), (r"courts of", r"exclusive jurisdiction", r"submit to the jurisdiction")),
    "arbitration": ((r"arbitration", r"dispute resolution", r"disputes"), (r"arbitrat", r"\blcia\b", r"\bicc\b", r"uncitral", r"\bdiac\b", r"\bsiac\b")),
    "confidentiality": ((r"confidential", r"non-disclosure"), (r"confidential", r"shall not disclose")),
    "ip": ((r"intellectual property", r"\bipr?\b", r"ownership of (?:documents|data|deliverables)", r"licen[cs]e"),
           (r"intellectual property", r"shall vest", r"background ip", r"royalty[- ]free")),
    "assignment": ((r"assignment", r"novation", r"transfer of (?:the )?(?:contract|agreement)"), (r"\bassign", r"novat")),
    "subcontracting": ((r"sub-?contract",), (r"sub-?contract",)),
    "scope_of_work": ((r"scope", r"services", r"the works", r"statement of work", r"description of (?:services|works)"),
                      (r"shall (?:provide|perform|supply|execute)", r"scope of (?:work|services)", r"appendix [a-z]\b")),
    "order_of_precedence": ((r"order of precedence", r"precedence", r"priority of documents", r"contract documents"),
                            (r"order of precedence", r"shall prevail", r"in the event of (?:any )?(?:conflict|inconsistency)")),
    "entire_agreement": ((r"entire agreement", r"whole agreement"), (r"entire agreement", r"supersedes all prior")),
    "notices": ((r"notices?\b", r"communications"), (r"notice shall be", r"deemed (?:to have been )?received", r"registered mail")),
    "change_of_control": ((r"change of control",), (r"change (?:of|in) (?:the )?control",)),
    "exclusivity": ((r"exclusiv", r"non-?compet"), (r"exclusive(?:ly)? (?:supplier|basis|right)", r"shall not (?:supply|provide) .* (?:competitor|any third party)", r"non-?compet")),
    "non_solicitation": ((r"non-?solicit", r"poaching"), (r"solicit", r"employ or engage")),
    "amendment": ((r"amendments?", r"variation of (?:the )?agreement", r"modification"), (r"amend", r"from time to time", r"no amendment")),
    # operational
    "mobilization": ((r"mobili[sz]",), (r"mobili[sz]",)),
    "equipment": ((r"equipment", r"tools", r"plant", r"materials"), (r"equipment", r"lost in hole", r"downhole", r"tools")),
    "personnel": ((r"personnel", r"key staff", r"key personnel", r"manning"), (r"personnel", r"key personnel", r"remove (?:any|from site)")),
    "standby": ((r"standby", r"waiting on", r"downtime"), (r"standby", r"stand-by", r"downtime")),
    "weather": ((r"weather", r"metocean"), (r"weather", r"sea state", r"waiting on weather")),
    "site_conditions": ((r"site conditions", r"ground conditions", r"unforeseen", r"site data", r"physical conditions"),
                        (r"site conditions", r"deemed to have (?:inspected|satisfied)", r"unforeseen", r"subsurface")),
    "client_dependencies": ((r"client[- ]furnished", r"company[- ]furnished", r"owner[- ]furnished", r"free[- ]issue", r"company obligations"),
                            (r"furnished", r"free[- ]issue", r"company shall provide", r"client shall provide")),
    "npt": ((r"non[- ]productive time", r"\bnpt\b", r"breakdown"), (r"non[- ]productive", r"\bnpt\b", r"zero rate", r"breakdown")),
    "backcharges": ((r"back[- ]?charge",), (r"back[- ]?charge", r"recover .* costs .* from the contractor")),
    # insurance/others already covered; kept last so earlier entries win ties
}


# ---------------------------------------------------------------------------
# Risk rules
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class Rule:
    id: str
    risk_type: str
    triggers: tuple[str, ...]
    description: str
    action: str
    severity: str = "medium"
    requires: tuple[str, ...] = ()
    scope: str = "sentence"
    unless: tuple[str, ...] = ()
    bands: tuple[str, str, tuple[tuple[float, str], ...], str | None] | None = None
    escalate: tuple[tuple[str, str], ...] = ()
    mitigate: tuple[tuple[str, str], ...] = ()
    context: tuple[tuple[str, str], ...] = ()
    effect: str = ""
    affected_party: str = "contractor"
    subcategories: tuple[str, ...] = field(default_factory=tuple)


def R(id: str, risk_type: str, triggers: tuple[str, ...], description: str, action: str, **kw) -> Rule:
    for key in ("requires", "unless"):
        if key in kw:
            kw[key] = _x(kw[key])
    for key in ("escalate", "mitigate", "context"):
        if key in kw:
            kw[key] = tuple((_x((p,))[0], v) for p, v in kw[key])
    return Rule(id=id, risk_type=risk_type, triggers=_x(triggers), description=description, action=action, **kw)


# bands = (metric, comparison, ((limit, severity), ...), otherwise)
#   metric: "days" | "percent" | "months"
#   comparison "ge": first band whose limit <= value; "le": first band whose limit >= value
#   otherwise: severity if no band matched, or None to not raise the finding

RULES: tuple[Rule, ...] = (
    # ------------------------------------------------------------------ LIABILITY
    R("LIA-01", "uncapped_liability",
      (r"without limit", r"unlimited liabilit", r"without (?:any )?limitation (?:as to|of) (?:amount|liability)",
       r"without regard to (?:the|any) (?:limitation|cap)", r"notwithstanding (?:clause \S+|any limitation|the limitation)",
       r"shall not be subject to (?:the|any) (?:limitation|cap)", r"no limit(?:ation)? (?:on|to) (?:the )?liabilit"),
      "Liability under this clause is not capped. Exposure is limited only by the size of the loss, and it sits outside any overall liability cap in the contract.",
      "Negotiate a cap (commonly a multiple of contract price or the insured limit), or confirm the exposure is fully insured and priced.",
      severity="critical", requires=(r"liab|indemnif|responsib|damages|loss",),
      escalate=((r"pollution|environment|third[- ]party|death|bodily injury", "critical"),),
      effect="Uncapped exposure outside the contract's liability ceiling."),
    R("LIA-02", "liability_cap_low",
      (r"aggregate liability .*shall not exceed", r"total liability .*shall not exceed", r"liability .*(?:is|shall be) (?:limited|capped) (?:to|at)",
       r"shall not exceed .*(?:contract price|contract value|fees? paid|annual)"),
      "The contract caps liability. Check the level against the value at risk and against uncapped carve-outs elsewhere, which can make the cap largely illusory.",
      "Confirm the cap covers all heads of claim and that carve-outs are limited to fraud, wilful misconduct and death or personal injury.",
      severity="low", bands=("percent", "le", ((10, "medium"), (50, "low")), "informational"),
      escalate=((r"gross negligence", "medium"), (r"except(?:ion)? .*(?:indemnit|confidential|intellectual property|data)", "medium")),
      context=((r"without limit|unlimited|without regard to (?:the|any) limitation", "high"),),
      effect="Caps overall exposure; value depends on carve-outs."),
    R("LIA-03", "consequential_loss_exposure",
      (r"liable for (?:all )?(?:direct and )?(?:indirect|consequential)", r"including (?:any )?(?:indirect|consequential) loss",
       r"loss of (?:profit|production|revenue|use) .*(?:shall be recoverable|shall be liable)"),
      "The contractor is exposed to indirect or consequential loss, including lost production or profit, which can dwarf the contract value.",
      "Insert a mutual exclusion of indirect and consequential loss, expressly covering loss of production, profit, and use.",
      severity="critical", unless=(r"neither party shall be liable .*(?:indirect|consequential)",)),
    R("LIA-04", "consequential_loss_exposure",
      (r"{C} shall not be liable .*(?:indirect|consequential)",),
      "The consequential loss exclusion protects only one party. The other side's indirect losses remain recoverable against the contractor.",
      "Make the exclusion mutual.", severity="medium",
      unless=(r"neither party", r"{K} shall not be liable .*(?:indirect|consequential)", r"each party")),
    R("LIA-05", "broad_indemnity",
      (r"indemnify,? (?:defend|protect)?,? ?(?:and )?(?:hold harmless|save harmless)", r"indemnif(?:y|ies) .*(?:any and all|all) (?:claims|losses|liabilities)",
       r"defend,? indemnify"),
      "A broad indemnity obliges the contractor to cover all claims and losses in its scope, including defence costs.",
      "Limit the indemnity to losses caused by the contractor's negligence or breach, proportionate to fault, and within the liability cap.",
      severity="high",
      escalate=((r"howsoever (?:caused|arising)|regardless of (?:fault|negligence)|whether or not caused by|even if caused by (?:the )?negligence", "critical"),
                (r"without limit|unlimited", "critical")),
      mitigate=((r"to the extent caused by|proportion(?:ate)? to|caused by the (?:negligence|breach) of the {C}", "medium"),)),
    R("LIA-06", "broad_indemnity",
      (r"(?:howsoever caused|regardless of (?:fault|negligence)|whether or not caused (?:in whole or in part )?by the negligence of (?:the )?{K})",),
      "The contractor must indemnify even for losses caused by the client's own negligence. This inverts normal risk allocation and is often uninsurable.",
      "Replace with a fault-based indemnity or a reciprocal knock-for-knock regime.", severity="critical"),
    R("LIA-07", "third_party_claim_exposure",
      (r"third[- ]party (?:claims|bodily injury|death|property)",),
      "The contractor carries third-party injury and property claims. Confirm the allocation is fault-based and matched by third-party liability insurance.",
      "Align third-party indemnities with fault and with the insured limit.", severity="medium",
      escalate=((r"without limit|unlimited", "critical"),)),
    R("LIA-08", "environmental_liability",
      (r"pollution", r"contamination", r"spill", r"environmental damage"),
      "The contractor bears pollution or environmental liability. These are among the largest claims in energy and construction work.",
      "Limit pollution liability to incidents originating from the contractor's equipment above surface, fault-based and capped, with reservoir and well pollution staying with the owner.",
      severity="high", requires=(r"liab|indemnif|responsible|bear",), escalate=((r"without limit|unlimited|regulatory penalt|fines", "critical"),)),
    R("LIA-09", "exclusive_remedy_limitation",
      (r"sole and exclusive remedy", r"exclusive remed"),
      "Remedies are restricted to those stated. Check which party benefits: an exclusive remedy for delay (liquidated damages) protects the contractor, one limiting the contractor's own claims does not.",
      "Confirm exclusive-remedy wording applies to the client's delay and defect claims, not only to the contractor's entitlements.",
      severity="low", escalate=((r"{C}'?s? sole (?:and exclusive )?remedy", "medium"),)),
    R("LIA-10", "limitation_period_extended",
      (r"(?:claims? may be (?:brought|made)|liability shall continue) .*(?:\d+|twelve|ten|six) \(?\d*\)? ?years",
       r"notwithstanding any (?:statutory )?limitation period", r"executed as a deed"),
      "The period in which claims can be brought is extended beyond the usual contractual limitation period, so exposure survives long after completion.",
      "Align the claims period with the warranty period or statutory default.", severity="medium"),
    R("LIA-11", "liability_cap_low",
      (r"liabilit\w* .*(?:shall not be limited|shall be unlimited) .*(?:gross negligence|wilful|fraud)",),
      "Carve-outs from the cap are drafted broadly. Gross negligence in particular is loosely defined in many jurisdictions and invites disputes about whether the cap applies.",
      "Define gross negligence or limit carve-outs to fraud and wilful misconduct.", severity="medium"),
    R("LIA-12", "unbalanced_risk_allocation",
      (r"{C} shall (?:assume|bear) (?:all|full|the entire) (?:risk|responsibility|liability)",
       r"at the (?:sole )?risk of the {C}", r"{C} shall be (?:solely|fully) responsible for"),
      "The contractor assumes all or full responsibility for a risk, typically regardless of cause.",
      "Limit to risks within the contractor's control; carve out client-caused and excepted risks.", severity="high"),

    # ------------------------------------------------------------------ COMMERCIAL
    R("COM-01", "payment_terms_unfavourable",
      (r"(?:pay|payment|paid|settle).{0,80}within .{0,30}\d+\)? (?:calendar |business )?days",
       r"(?:pay|payment|paid|settle).{0,80}within (?:thirty|forty|forty-five|fifty|sixty|seventy|eighty|ninety|one hundred)"),
      "Payment falls due {figure} after invoice. The longer the term, the more working capital the contractor finances on the client's behalf.",
      "Negotiate 30 days, interest on late payment, and a right to suspend for non-payment.",
      bands=("days", "ge", ((90, "high"), (60, "high"), (45, "medium"), (31, "low")), None),
      escalate=((r"undisputed|approved field tickets|certified", "medium"),)),
    R("COM-02", "pay_when_paid",
      (r"pay(?:ment)? when paid", r"pay if paid", r"(?:only )?(?:after|upon|following) (?:receipt|having received) (?:of )?payment from (?:the )?(?:owner|client|employer|end client)",
       r"conditional (?:up)?on (?:the )?{K} (?:having )?(?:received|being paid)"),
      "Payment is conditional on the client being paid upstream. The contractor carries the credit risk of a party it has no contract with. Such clauses are unenforceable in some jurisdictions but not all.",
      "Delete, or cap the waiting period and preserve the right to be paid regardless of upstream insolvency.", severity="critical"),
    R("COM-03", "set_off_rights_one_sided",
      (r"set[- ]off", r"deduct .*(?:from|against) any (?:amount|sum|payment)"),
      "The client may set off amounts it claims against sums due, reducing cash flow without a determination that the amount is owed.",
      "Limit set-off to amounts agreed or finally determined under this contract, and make it mutual.",
      severity="medium", escalate=((r"affiliate|any other (?:contract|agreement)|or otherwise|whether arising under", "high"),),
      unless=(r"(?:agreed|finally determined|undisputed) amounts? only",)),
    R("COM-04", "retention_exposure",
      (r"retain(?:ed|s)? .*\d+(?:\.\d+)?\s?%", r"retention of \d", r"retention .*\d+(?:\.\d+)?\s?%"),
      "The client retains {figure} of each payment, releasing it only at completion or later. That is cash earned but not received for the life of the job.",
      "Reduce retention, replace it with a retention bond, and tie release to objective events.",
      bands=("percent", "ge", ((15, "high"), (10, "medium"), (5, "low")), "low"),
      escalate=((r"(?:twelve|12|twenty-four|24) (?:\(\d+\) )?months (?:thereafter|after)", "medium"),)),
    R("COM-05", "price_escalation_unprotected",
      (r"firm and fixed", r"not (?:be )?subject to (?:any )?(?:adjustment|escalation|variation)", r"no (?:price )?(?:adjustment|escalation)",
       r"fixed (?:for|throughout) the (?:full |entire )?(?:term|duration)"),
      "Prices are fixed with no adjustment for inflation, labour, or material cost movements. Long durations turn this into a margin risk.",
      "Agree indexation after an initial fixed period, or a re-opener if costs move beyond a threshold.",
      severity="medium", escalate=((r"full term|entire (?:term|duration)|throughout the term|life of the (?:contract|agreement)", "high"),),
      mitigate=((r"first (?:twelve|12|eighteen|18) ", "low"),)),
    R("COM-06", "currency_exposure",
      (r"exchange rate risk", r"currency (?:risk|fluctuation)", r"exchange rate .*borne by", r"no adjustment .*exchange rate"),
      "Currency risk sits with the contractor: costs incurred in one currency are paid in another with no protection.",
      "Pay local costs in local currency, or agree an exchange-rate adjustment mechanism.", severity="medium"),
    R("COM-07", "tax_exposure",
      (r"responsible for (?:all|any) tax", r"withholding tax", r"taxes, duties,? (?:and|or) levies", r"inclusive of (?:all )?tax"),
      "The contractor bears taxes and withholding. Withholding deducted by the client reduces cash received and may not be recoverable.",
      "Gross-up for withholding tax, and allocate client-country taxes to the client.", severity="medium",
      escalate=((r"withholding", "medium"),), mitigate=((r"gross(?:ed)?[- ]up", "low"),)),
    R("COM-08", "cost_recovery_gap",
      (r"at no (?:additional|extra) (?:cost|charge)", r"deemed (?:to be )?included in the (?:rates|contract price|price)", r"no additional payment",
       r"shall not be entitled to (?:any )?(?:additional|extra) payment", r"at (?:its|the {C}'?s?) own (?:cost|expense)"),
      "Work or costs are deemed included in the price or at the contractor's own cost, removing any route to recover them.",
      "Price the obligation explicitly or make it a reimbursable/variation item.", severity="medium",
      unless=(r"mobili[sz]", r"defect", r"re-?perform", r"standby", r"weather", r"lost in hole", r"personnel",
              r"deductible", r"variation", r"accelerat"),
      escalate=((r"any and all|whatsoever|of whatever nature", "high"),)),
    R("COM-09", "invoice_rejection_risk",
      (r"(?:valid|correct) invoice", r"supporting documentation", r"approved (?:field tickets|timesheets)", r"invoice .*(?:rejected|returned)"),
      "Payment depends on invoice formalities or client-approved supporting documents, which the client controls and can delay.",
      "Add deemed approval of timesheets and field tickets if not disputed within a short period.", severity="low",
      escalate=((r"(?:rejected|returned) .*(?:entire|whole) invoice|withhold (?:payment of )?the (?:entire|whole)", "medium"),)),
    R("COM-10", "late_payment_interest_absent",
      (r"(?:no|without) interest (?:shall be )?(?:payable|due|on late)", r"shall not be (?:liable|entitled) (?:to|for) (?:any )?interest"),
      "Late payment carries no interest, so the client bears no cost for paying late.",
      "Insert statutory or contractual interest on overdue sums.", severity="medium"),
    R("COM-11", "audit_exposure",
      (r"\baudit\b", r"inspect .*(?:books|records|accounts)", r"access to .*(?:books|records)"),
      "The client may audit the contractor's books and records. Broad audit rights reach margins, overheads, and supplier pricing.",
      "Limit audits to reimbursable costs and variations, exclude fixed rates and profit, and cap the look-back period.",
      severity="low", escalate=((r"any time|at all times|(?:five|six|seven|ten|5|6|7|10) \(?\d*\)? ?years|lump sum|fixed rates", "medium"),)),
    R("COM-12", "unilateral_variation",
      (r"{K} may (?:at any time )?(?:instruct|order|direct|require) (?:a )?(?:variation|change)",
       r"variation .*value(?:d)? .*(?:by|at the discretion of) the {K}", r"{C} shall (?:proceed|comply) with (?:any|the) (?:instructed )?variation"),
      "The client can vary the scope and the contractor must proceed, typically before the price or time impact is agreed.",
      "Require agreement of price and time before proceeding, or at least a fair valuation mechanism and time relief.",
      severity="medium", escalate=((r"discretion|as determined by the {K}|shall not (?:delay|refuse)", "high"),)),
    R("COM-13", "variation_claim_time_bar",
      (r"failing which", r"(?:shall be )?deemed to have waived", r"waives? (?:its|all|any) (?:right|entitlement|claim)", r"time[- ]barred",
       r"shall not be entitled to .*(?:unless|if) .*notice"),
      "Entitlements are lost if notice or a claim is not submitted within {figure}. A missed deadline forfeits a legitimate claim outright.",
      "Extend the period, make notice a matter of good practice rather than a condition precedent, and avoid automatic waiver.",
      severity="high", bands=("days", "le", ((7, "critical"), (14, "high"), (28, "medium")), "medium")),
    R("COM-14", "backcharge_exposure",
      (r"back[- ]?charge", r"recover .*(?:costs|expenses) .*from the {C}", r"deduct .*(?:costs|expenses) incurred by the {K}"),
      "The client may recover its own costs from the contractor by back-charge or deduction, often without a prior agreement on the amount.",
      "Require notice, substantiation, and a chance to remedy before any back-charge.", severity="medium"),
    R("COM-15", "payment_security_gap",
      (r"advance payment (?:guarantee|bond|security)",),
      "An advance payment must be secured by a guarantee, typically on-demand, which ties up credit lines.",
      "Make the guarantee reduce as the advance is recovered and expire on full recovery.", severity="low"),
    R("COM-16", "sole_discretion",
      (r"(?:sole|absolute|unfettered) discretion", r"as (?:determined|decided) by the {K}", r"in the (?:sole )?opinion of the {K}",
       r"to the (?:entire )?satisfaction of the {K}"),
      "A decision that affects the contractor is left to the client's discretion or opinion, with no objective standard.",
      "Replace with 'acting reasonably' and objective criteria.", severity="medium",
      escalate=((r"absolute|unfettered|sole discretion", "high"),)),

    # ------------------------------------------------------------------ SCHEDULE
    R("SCH-01", "liquidated_damages_exposure",
      (r"liquidated damages", r"delay damages"),
      "Liquidated damages apply for delay. The rate and whether there is an overall cap determine the real exposure.",
      "Confirm an aggregate cap (commonly 5-15% of contract price), that LDs are the sole remedy for delay, and that time relief is available for client delays.",
      severity="high", mitigate=((r"capped|shall not exceed|maximum (?:aggregate )?(?:amount|liability)|limited to", "medium"),),
      escalate=((r"without prejudice to|in addition to (?:any|its) other|not (?:be )?the (?:sole|exclusive) remedy", "critical"),),
      context=((r"extension of time only|shall not entitle .*extension", "high"),)),
    R("SCH-02", "liquidated_damages_exposure",
      (r"(?:penalty|penalties) (?:of|for|shall)", r"shall pay (?:a )?penalt"),
      "The clause is drafted as a penalty. Depending on governing law this may be unenforceable, which cuts both ways: uncertainty for both parties.",
      "Redraft as a genuine pre-estimate of loss with a cap.", severity="medium"),
    R("SCH-03", "milestone_commitment_risk",
      (r"shall (?:achieve|complete|reach) .*by \d{1,2} (?:january|february|march|april|may|june|july|august|september|october|november|december)",
       r"(?:completion|milestone) date(?:s)? (?:is|are|shall be) \d", r"time (?:shall be|is) of the essence"),
      "Performance is tied to fixed calendar dates rather than durations from an agreed start. Late access or approvals compress the contractor's window.",
      "Express milestones as durations from notice to proceed, with relief for client-caused delay.",
      severity="medium", escalate=((r"time (?:shall be|is) of the essence", "high"),)),
    R("SCH-04", "extension_of_time_restricted",
      (r"extension of time only", r"(?:only|solely) (?:be )?entitled to an extension", r"shall not (?:be entitled to|entitle .*to) (?:an )?extension",
       r"no extension of time"),
      "Time relief is available only in narrow circumstances. Delays outside those events expose the contractor to liquidated damages even when it is not at fault.",
      "Add client-caused delay, variations, excepted risks, and changes in law as extension events.", severity="high"),
    R("SCH-05", "strict_notice_requirement",
      (r"(?:written )?notice .*within .{0,30}\d+\)? (?:calendar |business )?days of (?:the {C} )?becoming aware",
       r"condition precedent"),
      "Relief depends on notice being given within {figure}. Operational teams rarely notify that fast, and a late notice may forfeit the entitlement.",
      "Extend the notice period and remove condition-precedent wording.",
      severity="medium", bands=("days", "le", ((7, "high"), (14, "medium")), "low")),
    R("SCH-06", "force_majeure_narrow",
      (r"shall not (?:constitute|be considered|be deemed) (?:a )?force majeure", r"force majeure (?:shall )?(?:mean|means) .*only",
       r"(?:excluding|except|other than) .*(?:weather|strikes|labour disputes|supply chain|shortage)"),
      "Force majeure is narrowly defined and excludes events the contractor cannot control, such as weather, strikes, or supply-chain disruption.",
      "Widen the definition to include those events, or give time relief (without cost) for them.", severity="medium",
      escalate=((r"weather|epidemic|pandemic|supply chain", "high"),)),
    R("SCH-07", "force_majeure_narrow",
      (r"force majeure .*(?:no|without) (?:payment|compensation)", r"(?:no|not be entitled to) (?:any )?(?:payment|compensation|standby) .*force majeure"),
      "During force majeure the contractor receives nothing, while its equipment and personnel remain committed.",
      "Agree a reduced force majeure rate and a termination right if it persists.", severity="medium"),
    R("SCH-08", "delay_risk",
      (r"accelerat\w* .*(?:at (?:its|the {C}'?s?) own cost|without (?:additional )?(?:cost|payment))",),
      "The client can require acceleration at the contractor's cost.",
      "Make acceleration a paid variation unless the contractor is in culpable delay.", severity="high"),
    R("SCH-09", "delivery_obligation_strict",
      (r"\b(?:ddp|delivered duty paid)\b", r"risk .*shall remain with the {C} until (?:final )?acceptance"),
      "Delivery terms leave transit risk, duties, and import formalities with the supplier until delivery at site or acceptance.",
      "Price duties and logistics, confirm insurance covers transit, and consider DAP/FCA instead.", severity="medium"),

    # ------------------------------------------------------------------ PERFORMANCE
    R("PER-01", "performance_guarantee_exposure",
      (r"on[- ]demand", r"(?:performance|bank) (?:guarantee|bond|security)", r"parent company guarantee"),
      "Security is required in favour of the client. {figure} of contract value is committed and reduces credit capacity.",
      "Prefer a conditional (default) bond, reduce the amount, and set an expiry at completion.",
      severity="medium", bands=("percent", "ge", ((20, "high"), (10, "medium")), "medium"),
      escalate=((r"on[- ]demand|first demand|unconditional", "high"),)),
    R("PER-02", "warranty_period_onerous",
      (r"warrant\w* .*(?:period|for) .{0,20}\d+\)? months", r"(?:warranty|defects liability|defects notification) period .*\d+\)? (?:months|years)"),
      "The warranty or defects period runs for {figure}. Longer periods extend liability, retention, and security.",
      "Align to 12 months from acceptance with an overall long-stop, and exclude wear, misuse, and client-supplied items.",
      bands=("months", "ge", ((36, "high"), (24, "high"), (13, "medium")), "low")),
    R("PER-03", "defects_liability_exposure",
      (r"re-?perform .*(?:at (?:its|the {C}'?s?) own cost)", r"(?:including|together with) (?:all )?(?:associated )?(?:vessel|access|removal|reinstallation|transport|mobili[sz]ation)",
       r"remedy .*defects? .*at (?:its|the {C}'?s?) own (?:cost|expense)"),
      "Remedying defects is at the contractor's cost, including access, vessels, and re-mobilisation. Offshore these costs can exceed the value of the work being fixed.",
      "Exclude access and logistics costs, or cap total defect costs.", severity="high"),
    R("PER-04", "fitness_for_purpose",
      (r"fit (?:for|to) (?:the|its) (?:intended )?purpose", r"fitness for purpose"),
      "A fitness-for-purpose obligation is strict: the contractor is liable if the result fails, even with no negligence. It is usually not covered by professional indemnity insurance.",
      "Replace with reasonable skill and care, or tie it to an objective specification.", severity="high"),
    R("PER-05", "design_responsibility",
      (r"responsible for (?:the )?design", r"(?:approval|review|acceptance) (?:by the {K} )?(?:of .* )?shall not relieve",
       r"notwithstanding (?:any )?(?:approval|review|consent) (?:of|by) the {K}"),
      "Design responsibility rests with the contractor even where the client has reviewed or approved it, including errors in client-provided designs if adopted.",
      "Exclude client-supplied design and data, and limit liability to reasonable skill and care.", severity="high"),
    R("PER-06", "sla_credit_exposure",
      (r"service credit", r"(?:availability|uptime) of \d", r"service levels?", r"response time"),
      "Performance is measured against service levels with financial consequences.",
      "Cap service credits (often 10-20% of monthly fees), make them the sole remedy for the failure, and exclude client-caused and third-party outages.",
      severity="medium", escalate=((r"uncapped|without limit|in addition to (?:any )?other", "high"),),
      mitigate=((r"sole (?:and exclusive )?remedy|capped|shall not exceed", "low"),)),
    R("PER-07", "kpi_penalty_exposure",
      (r"\bkpis?\b", r"key performance indicator"),
      "KPIs are defined with consequences. Check whether failing a KPI reduces payment or triggers termination.",
      "Tie KPIs to measurable, contractor-controlled outputs, with a cure period.", severity="low",
      escalate=((r"terminat|deduct|reduc", "medium"),)),
    R("PER-08", "acceptance_criteria_unclear",
      (r"to the (?:entire )?satisfaction of the {K}", r"acceptance .*(?:discretion|opinion)", r"(?:reject|refuse) .*for any reason"),
      "Acceptance depends on the client's satisfaction rather than objective tests, which also delays payment, retention release, and the start of warranty.",
      "Define acceptance tests and deemed acceptance if the client doesn't respond within a set period.", severity="medium"),
    R("PER-09", "unbalanced_risk_allocation",
      (r"(?:highest|best) (?:industry )?(?:standard|practice)", r"best endeavou?rs", r"utmost (?:skill|care)"),
      "The standard of performance is set above the ordinary reasonable skill and care, which increases liability and may exceed insurance cover.",
      "Use 'reasonable skill, care and diligence' or 'good industry practice'.", severity="medium"),
    R("PER-10", "title_risk_transfer",
      (r"title .*shall pass .*(?:on|upon) (?:delivery|shipment|manufacture)", r"risk (?:of loss )?.*shall (?:remain|pass) .*(?:until|upon) (?:final )?acceptance",
       r"title .*(?:upon|on) payment"),
      "Title and risk pass at different points, or risk stays with the supplier until acceptance. Goods may be at the supplier's risk while in the client's custody.",
      "Pass risk with title at delivery, and make the client insure goods in its custody.", severity="medium"),

    # ------------------------------------------------------------------ TERMINATION
    R("TER-01", "termination_for_convenience_exposure",
      (r"terminat\w* .*for (?:its|their) (?:own )?convenience", r"terminat\w* .*without (?:cause|reason)", r"terminat\w* .*at any time for any reason"),
      "The client may terminate without cause on {figure} notice. The contractor risks stranded costs: demobilisation, committed subcontracts, and lost margin.",
      "Secure payment for work done, demobilisation, committed costs, and a fair share of lost profit, with a longer notice period.",
      bands=("days", "le", ((7, "critical"), (14, "high"), (30, "medium")), "medium")),
    R("TER-02", "termination_payment_unclear",
      (r"no (?:claim|entitlement) (?:for|to) (?:loss of )?(?:profit|demobili[sz]ation|overhead|unrecovered)",
       r"(?:shall not be entitled to|excluding) .*(?:loss of profit|demobili[sz]ation|overhead|committed costs)",
       r"(?:only|solely) (?:for|pay for) .*(?:properly )?performed (?:up )?to the date of termination"),
      "On termination the contractor recovers only work performed, not demobilisation, committed costs, or overhead. Early termination can turn a profitable contract into a loss.",
      "Add demobilisation, cancellation charges, committed costs, and a termination fee.",
      severity="high", escalate=((r"no (?:claim|entitlement)|shall have no claim", "high"),)),
    R("TER-03", "termination_notice_short",
      (r"fails? to remedy .*within .{0,20}\d+\)? days", r"terminate .*(?:immediately|forthwith)", r"material breach"),
      "The client may terminate for default with a short cure period, or immediately.",
      "Extend the cure period and require a prior default notice specifying the breach.",
      severity="medium", bands=("days", "le", ((7, "high"), (14, "medium")), "low"),
      escalate=((r"any breach|breach of any (?:term|provision)", "high"),)),
    R("TER-04", "suspension_exposure",
      (r"suspend .*(?:at any time|for any reason|for its convenience)", r"suspen\w* .*without (?:payment|compensation)",
       r"suspend the (?:works|services) .*without payment"),
      "The client may suspend the work at will. Standby costs, idle crews, and remobilisation fall on the contractor unless paid.",
      "Pay standby during suspension, and give a right to terminate if suspension exceeds a set period.",
      severity="high", escalate=((r"without payment|sole remedy", "high"),)),
    R("TER-05", "step_in_rights",
      (r"step[- ]in", r"take over (?:the )?(?:performance of the )?(?:works|services)", r"use the {C}'?s? (?:equipment|materials|plant)"),
      "The client may step in, take over the work, or use the contractor's equipment, typically at the contractor's cost.",
      "Limit to genuine default after notice, return equipment in the same condition, and cap recoverable costs.", severity="high"),
    R("TER-06", "change_of_control_trigger",
      (r"change (?:of|in) (?:the )?control",),
      "A change of ownership of the contractor allows the client to terminate. Corporate transactions can put the contract at risk.",
      "Limit to changes in favour of a competitor or sanctioned party, or require consent not unreasonably withheld.", severity="medium"),
    R("TER-07", "auto_renewal",
      (r"automatically (?:renew|extend)", r"shall renew (?:automatically|for successive)"),
      "The agreement renews automatically unless notice is given, locking in rates for another term.",
      "Diarise the notice date, or make renewal subject to agreeing revised rates.", severity="low",
      escalate=((r"same (?:rates|prices|terms)", "medium"),)),

    # ------------------------------------------------------------------ INSURANCE
    R("INS-01", "insurance_limits_low",
      (r"insurance .*(?:limit|not less than|minimum)", r"(?:limit|cover) of (?:not less than )?(?:USD|US\$|EUR|GBP|QAR|AED|\$)"),
      "Specific insurance limits are required: {figure}. Confirm the contractor's programme meets them and that the premium is priced.",
      "Check each policy limit against the requirement and against uncapped indemnities in the contract.",
      severity="low", context=((r"without limit|unlimited", "medium"),)),
    R("INS-02", "deductible_exposure",
      (r"deductibles? .*(?:{C}'?s? account|borne by the {C}|for the account of the {C})", r"excess .*borne by the {C}"),
      "Policy deductibles are for the contractor's account, so smaller claims are effectively uninsured.",
      "Confirm deductible levels and price them.", severity="medium"),
    R("INS-03", "insurance_coverage_gap",
      (r"waive\w* .*subrogation", r"(?:name|named|include) .*(?:as )?(?:an )?additional insured", r"co-?insured"),
      "The contractor's policies must name the client as insured and/or waive subrogation, which may require insurer endorsement and extra premium.",
      "Confirm with the broker that endorsements are available and limit them to liabilities assumed under the contract.", severity="low"),
    R("INS-04", "insurance_coverage_gap",
      (r"(?:insurance|policies) .*(?:shall not|does not) (?:limit|relieve)", r"notwithstanding (?:any )?insurance"),
      "Liability is not limited to insurance recoveries, so uninsured losses fall on the contractor's balance sheet.",
      "Where possible, cap liability at the insured amount.", severity="low"),
    R("INS-05", "insurance_coverage_gap",
      (r"(?:for|during) (?:a period of )?.{0,20}\d+\)? months? (?:thereafter|after (?:completion|termination|expiry))",),
      "Insurance must be kept in force after the contract ends, adding cost beyond the contract term.",
      "Price run-off cover, or limit to professional indemnity only.", severity="low", requires=(r"insur|maintain",)),

    # ------------------------------------------------------------------ COMPLIANCE
    R("CMP-01", "hse_obligation_exposure",
      (r"(?:trir|ltif|recordable incident|lost time) .*(?:not exceed|exceeding|below)", r"hse .*(?:suspend|terminat|without payment)",
       r"breach of (?:this clause|hse|safety) .*(?:suspend|terminat)"),
      "HSE performance thresholds carry commercial consequences: suspension without payment or termination.",
      "Apply consequences only to serious or repeated breaches after a remediation plan.",
      severity="medium", escalate=((r"without payment|terminat", "high"),)),
    R("CMP-02", "regulatory_compliance_burden",
      (r"(?:policies|procedures|standards|rules|requirements) .*(?:as (?:amended|updated|revised) from time to time)",
       r"comply with (?:all )?(?:the )?{K}'?s? (?:policies|procedures|standards)"),
      "The contractor must comply with client policies that the client can change unilaterally, which moves cost onto the contractor.",
      "Freeze policies at contract date, with changes treated as variations.", severity="medium"),
    R("CMP-03", "sanctions_exposure",
      (r"sanction", r"anti-?bribery|anti-?corruption|brib|facilitation payment"),
      "Compliance warranties on bribery or sanctions with immediate termination for breach, sometimes extending to subcontractors and affiliates.",
      "Accept the obligation but limit it to matters within the contractor's knowledge and control, with a proportionate termination trigger.",
      severity="medium", escalate=((r"immediately|forthwith|without (?:notice|liability)", "medium"),),
      mitigate=((r"to the best of|knowledge", "low"),)),
    R("CMP-04", "export_control_exposure",
      (r"export control", r"re-?export", r"dual[- ]use", r"end[- ]user"),
      "Export control obligations apply; licensing delays can hold up delivery and put the contractor in breach.",
      "Give time relief for licence delays outside the contractor's control.", severity="medium"),
    R("CMP-05", "local_content_obligation",
      (r"local content", r"in[- ]country value", r"\bicv\b", r"nationali[sz]ation"),
      "A local content commitment is part of the contract. Shortfalls may carry penalties or affect future awards.",
      "Commit only to achievable levels and define how the percentage is measured.", severity="low",
      escalate=((r"penalt|liquidated|deduct|terminat", "medium"),)),
    R("CMP-06", "data_protection_exposure",
      (r"personal data", r"data protection", r"\bgdpr\b", r"data subject", r"data controller|data processor"),
      "Data protection obligations apply. Regulatory fines and breach notification duties can be substantial.",
      "Define controller/processor roles, cap liability for data breaches, and align notification periods with the law.",
      severity="medium", escalate=((r"without limit|unlimited|indemnif", "high"),)),
    R("CMP-07", "cyber_security_obligation",
      (r"cyber", r"information security", r"iso ?27001", r"security incident"),
      "Cyber security controls and incident reporting duties apply, typically with tight notification windows ({figure}).",
      "Confirm the controls exist, and that notification periods run from confirmation of an incident, not suspicion.",
      severity="medium", bands=("days", "le", ((1, "medium"),), "low")),
    R("CMP-08", "regulatory_compliance_burden",
      (r"(?:obtain|maintain) (?:all )?(?:necessary |required )?(?:permits|licen[cs]es|approvals|consents)",),
      "The contractor must obtain permits and approvals. Delays caused by authorities may not give time relief.",
      "Allocate client-side permits to the client, and give time relief for authority delays.", severity="low"),
    R("CMP-09", "regulatory_compliance_burden",
      (r"change in (?:law|legislation)",),
      "A change-in-law clause exists. Check whether it gives price and time relief to the contractor.",
      "Ensure changes in law after bid date are compensated.", severity="informational",
      escalate=((r"(?:no|shall not) .*(?:adjust|relief|entitle)", "high"),)),

    # ------------------------------------------------------------------ CONTRACTUAL
    R("CON-01", "dispute_resolution_unfavourable",
      (r"arbitrat", r"(?:exclusive )?jurisdiction of the courts", r"courts of"),
      "Disputes go to the stated forum. Seat, rules, number of arbitrators, and costs rules determine how expensive a dispute is.",
      "Prefer a neutral seat and institution, with a tiered escalation step before formal proceedings.",
      severity="low", escalate=((r"costs .*(?:borne by|paid by) the (?:unsuccessful|losing)|three arbitrators|exclusive jurisdiction of the courts of", "low"),)),
    R("CON-02", "governing_law_unfavourable",
      (r"governed by (?:and construed in accordance with )?the laws? of",),
      "The contract is governed by the stated law. The contractor's rights on penalties, caps, and time bars depend on it.",
      "Take local legal advice where the law is unfamiliar.", severity="informational"),
    R("CON-03", "confidentiality_obligation",
      (r"confidential", r"shall not disclose"),
      "Confidentiality obligations apply for {figure} or longer.",
      "Allow disclosure to insurers, lenders, advisers, and as required by law; limit duration.", severity="informational",
      escalate=((r"perpetu|indefinitely|without limit of time|survive (?:any )?terminat", "low"),)),
    R("CON-04", "ip_rights_transfer",
      (r"(?:shall )?vest in the {K}", r"(?:assign|transfer)s? .*(?:all )?(?:right,? title and interest|intellectual property)",
       r"(?:irrevocable|perpetual),? (?:worldwide,? )?(?:royalty[- ]free )?licen[cs]e", r"background (?:ip|intellectual property)"),
      "Intellectual property in deliverables passes to the client, and background IP may be licensed irrevocably. This can prevent reuse of know-how and tools.",
      "Keep background IP, grant only a licence limited to the project, and exclude pre-existing tools and methods.",
      severity="medium", escalate=((r"background|pre-?existing|all (?:intellectual property|ip)", "high"),)),
    R("CON-05", "assignment_restriction",
      (r"{C} shall not (?:assign|novate|transfer)", r"assign .*(?:without the prior written consent)"),
      "The contractor cannot assign without consent. Check whether the client can assign freely: an asymmetric right.",
      "Make assignment restrictions mutual, with consent not unreasonably withheld, and permit assignment to affiliates or financiers.",
      severity="low", escalate=((r"absolute discretion|sole discretion", "medium"),)),
    R("CON-06", "subcontracting_restriction",
      (r"shall not sub-?contract", r"sub-?contract .*(?:prior (?:written )?approval|consent)", r"(?:fully )?(?:liable|responsible) for the acts (?:and|or) omissions of (?:its |any )?sub-?contractors?"),
      "Subcontracting needs approval and the contractor is fully liable for subcontractors. Liability flows up without always flowing down.",
      "Pre-approve key subcontractors, and ensure back-to-back terms in subcontracts.", severity="low"),
    R("CON-07", "order_of_precedence_risk",
      (r"order of precedence", r"shall (?:take )?prevail", r"in the event of (?:any )?(?:conflict|inconsistency|discrepancy)"),
      "An order of precedence resolves conflicts between documents. Where the contractor's proposal ranks last, its qualifications and assumptions may be overridden.",
      "Ensure agreed clarifications and the contractor's proposal rank above generic client specifications.",
      severity="low", escalate=((r"(?:proposal|tender|bid|offer) .*(?:lowest|last|shall not form part)", "high"),)),
    R("CON-08", "entire_agreement_exclusion",
      (r"entire agreement", r"supersedes all (?:prior|previous)"),
      "The written contract replaces everything agreed before it, including pre-contract clarifications and bid assumptions not repeated in it.",
      "Incorporate the agreed clarification log and bid qualifications into the contract.", severity="low"),
    R("CON-09", "strict_notice_requirement",
      (r"notice shall (?:only )?be (?:valid|effective|deemed)", r"(?:not|no) (?:be )?(?:valid|effective) (?:if|when) (?:sent|given) by (?:e-?mail|electronic)",
       r"(?:by hand|registered (?:mail|post)|courier) (?:only)?"),
      "Notices are only valid in a prescribed form or delivery method. Notices sent informally, such as by email, may be invalid.",
      "Permit email notices to named addresses and confirm the notice procedure with operational teams.", severity="low"),
    R("CON-10", "exclusivity_restriction",
      (r"exclusive(?:ly)? (?:supplier|basis|right)", r"non-?compet", r"shall not (?:provide|supply|perform) (?:similar|the same|any) (?:services|goods) (?:to|for) (?:any )?(?:competitor|third part)"),
      "The contractor is restricted from working for others, which limits future business.",
      "Limit scope, territory, and duration, and make it reciprocal with committed volumes.", severity="high"),
    R("CON-11", "non_solicitation_restriction",
      (r"solicit", r"(?:employ|engage|hire) .*(?:personnel|employees|staff) of"),
      "Non-solicitation restricts hiring the other party's staff.", "Make it mutual, time-limited, and exclude general advertising.",
      severity="informational"),
    R("CON-12", "unilateral_amendment",
      (r"{K} may (?:amend|vary|modify|update) (?:this agreement|the terms|these terms|the (?:rates|prices|fees))",
       r"may (?:increase|change) (?:the )?(?:fees|prices|rates) (?:on|by|upon) (?:notice|giving)"),
      "One party can change the terms or prices unilaterally.", "Require written agreement of both parties for any amendment.",
      severity="high"),
    R("CON-13", "back_to_back_gap",
      (r"back[- ]to[- ]back", r"(?:main|head|prime) contract .*(?:incorporated|apply)", r"flow[- ]?down"),
      "Obligations are flowed down from a head contract the contractor may not have seen. Gaps between the two leave the contractor exposed.",
      "Obtain the head contract terms and check that entitlements flow down as well as obligations.", severity="medium"),

    # ------------------------------------------------------------------ OPERATIONAL
    R("OPS-01", "mobilization_cost_risk",
      (r"mobili[sz]ation (?:and demobili[sz]ation )?(?:costs|charges|fees)? ?(?:shall be )?(?:borne by|at the (?:cost|expense) of|for the account of) the {C}",
       r"(?:no|not be entitled to) .*mobili[sz]ation (?:fee|charge|payment)", r"mobili[sz]ation .*at (?:its|the {C}'?s?) own cost"),
      "Mobilisation and demobilisation costs are for the contractor's account. On a short or terminated job they may never be recovered.",
      "Price a lump-sum mobilisation fee payable on arrival, and demobilisation on release.", severity="medium"),
    R("OPS-02", "standby_rate_gap",
      (r"standby .*(?:only|limited to|for the first)", r"(?:beyond|in excess of|after) .{0,30}\d+\)? (?:hours|days) .*(?:at the {C}'?s? cost|no (?:payment|charge))",
       r"(?:zero|nil|no) (?:standby )?rate"),
      "Standby is paid only for a limited period or not at all. Idle time beyond it is unpaid while crews and equipment remain committed.",
      "Pay standby for the full duration of client-caused or weather downtime, or give a release right.", severity="high"),
    R("OPS-03", "weather_risk_unallocated",
      (r"weather", r"sea state", r"metocean"),
      "Weather downtime is addressed. Check who pays for waiting on weather and whether it gives time relief.",
      "Treat waiting on weather as paid standby with time relief.", severity="low", requires=(r"cost|pay|rate|standby|extension|relief|risk",),
      escalate=((r"(?:at|for) the {C}'?s? (?:cost|account|risk)|shall not (?:constitute|be) force majeure|no (?:payment|standby)", "high"),)),
    R("OPS-04", "client_dependency_risk",
      (r"(?:client|company|owner|employer)[- ]furnished", r"free[- ]issue", r"(?:{K}) shall (?:provide|supply|furnish)"),
      "The contractor depends on items or services the client provides. Delay or defects in them should give relief.",
      "Tie each client-furnished item to a date, with time and cost relief if late or defective.",
      severity="low", escalate=((r"shall not (?:entitle|give rise to) .*(?:extension|additional)|no extension", "high"),)),
    R("OPS-05", "latent_conditions_risk",
      (r"deemed to have (?:inspected|examined|satisfied (?:itself|himself))", r"(?:unforeseen|unforeseeable) .*(?:{C}'?s? risk|no (?:extension|additional))",
       r"(?:site|ground|subsurface|physical) conditions .*(?:{C}'?s? risk|borne by the {C})", r"(?:accuracy|adequacy) of (?:the )?(?:site )?(?:data|information)"),
      "The contractor takes the risk of site or ground conditions it could not reasonably foresee, and of inaccurate client-provided data.",
      "Share unforeseeable-conditions risk (relief for conditions an experienced contractor could not have foreseen) and let the contractor rely on client data.",
      severity="high"),
    R("OPS-06", "cost_recovery_gap",
      (r"lost (?:or damaged )?in (?:the )?hole", r"downhole (?:equipment|tools) .*(?:{C}'?s? (?:cost|risk|account))", r"loss of (?:or damage to )?(?:the )?{C}'?s? equipment .*(?:{C}'?s? (?:cost|risk))"),
      "Loss of or damage to the contractor's equipment in the client's operations (for example lost in hole) is at the contractor's cost.",
      "Make the client pay replacement cost less depreciation for equipment lost in hole or in the well.", severity="high"),
    R("OPS-07", "standby_rate_gap",
      (r"non[- ]productive time", r"\bnpt\b", r"breakdown .*(?:zero|nil|no) rate", r"(?:zero|nil) rate"),
      "Non-productive time or breakdown is unpaid. Long breakdowns may also allow termination.",
      "Allow a monthly breakdown allowance at reduced rate before zero rate applies.", severity="medium"),
    R("OPS-08", "cost_recovery_gap",
      (r"(?:remove|replace) (?:any )?(?:personnel|person|member of (?:the )?(?:crew|staff)) .*(?:at (?:its|the {C}'?s?) own cost|without (?:cost|charge))",
       r"key personnel .*(?:shall not be (?:removed|replaced|changed)|without the (?:prior )?(?:written )?(?:consent|approval))"),
      "The client can demand removal of personnel at the contractor's cost, or restricts replacing key personnel.",
      "Require reasonable grounds for removal, and a right to substitute with equivalent people.", severity="medium"),

    # ------------------------------------------------------------------ SCOPE / CROSS-CUTTING
    R("GEN-01", "scope_ambiguity",
      (r"including (?:but not limited to|without limitation)", r"(?:all|any) (?:other )?(?:work|services|items) (?:necessary|required|reasonably inferable)",
       r"whether or not (?:specifically )?(?:mentioned|described|specified)", r"(?:as|where) (?:may be )?(?:reasonably )?(?:required|instructed) by the {K}"),
      "Scope is open-ended: the contractor must perform anything necessary or reasonably inferable, beyond what is priced.",
      "Define scope by reference to a closed specification, with anything else a variation.", severity="medium"),
    R("GEN-02", "unbalanced_risk_allocation",
      (r"{K} (?:shall|will) (?:not|have no) (?:be )?(?:liab|responsib)", r"without (?:any )?(?:liability|recourse) (?:to|on the part of) the {K}"),
      "The client disclaims liability for its own obligations or information.", "Reinstate client responsibility for its own acts, data, and obligations.",
      severity="medium"),
)


# ---------------------------------------------------------------------------
# Contract-wide protections a well-drafted contract should contain.
# Checked across the whole contract; absence becomes a finding.
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class Protection:
    risk_type: str
    category: str
    severity: str
    present_if: tuple[str, ...]
    description: str
    action: str
    only_if: tuple[str, ...] = ()  # only check when the contract contains these


PROTECTIONS: tuple[Protection, ...] = (
    Protection("uncapped_liability", "liability", "critical",
               (r"aggregate liability", r"limitation of liability", r"total liability", r"liabilit\w* .*shall not exceed", r"liabilit\w* .*(?:limited|capped) (?:to|at)"),
               "No overall limitation of liability was identified. The contractor's exposure under the contract is unlimited.",
               "Insert an aggregate liability cap tied to contract value, with narrow carve-outs."),
    Protection("consequential_loss_exposure", "liability", "high",
               (r"consequential", r"indirect loss", r"loss of (?:profit|production|use)"),
               "No exclusion of indirect or consequential loss was identified, so lost production or profit claims remain open.",
               "Insert a mutual exclusion of indirect and consequential loss."),
    Protection("force_majeure_narrow", "schedule", "high",
               (r"force majeure", r"exceptional event", r"act of god"),
               "No force majeure clause was identified. Events outside either party's control give no relief from delay or non-performance.",
               "Insert a force majeure clause with time relief and a termination right for prolonged events."),
    Protection("extension_of_time_restricted", "schedule", "medium",
               (r"extension of time", r"extend the (?:time|completion date|programme)", r"time relief"),
               "No extension of time mechanism was identified. Delay caused by the client or by variations may still expose the contractor to delay damages.",
               "Insert extension-of-time events including client delay and variations.",
               only_if=(r"liquidated damages", r"delay damages", r"completion date", r"milestone")),
    Protection("unilateral_variation", "commercial", "medium",
               (r"variation", r"change order", r"change request", r"changes? (?:in|to) (?:the )?scope"),
               "No variation or change mechanism was identified, so there is no agreed route to price scope changes.",
               "Insert a variation procedure with valuation and time impact."),
    Protection("payment_terms_unfavourable", "commercial", "high",
               (r"\bpay\b", r"payment", r"invoice"),
               "No payment terms were identified.", "Insert payment timing, invoicing, and currency terms."),
    Protection("late_payment_interest_absent", "commercial", "low",
               (r"interest (?:on|at|shall (?:accrue|be payable))", r"late payment (?:interest|charge)", r"overdue (?:sums|amounts|payments) .*interest"),
               "No interest on late payment was identified. The client bears no cost for paying late.",
               "Insert interest on overdue sums.", only_if=(r"\bpay\b", r"invoice")),
    Protection("suspension_exposure", "termination", "medium",
               (r"{C} may suspend", r"(?:right|entitled) to suspend .*(?:non-?payment|payment)", r"suspend .*(?:for|in the event of) non-?payment"),
               "The contractor has no right to suspend work for non-payment, leaving it to keep performing while unpaid.",
               "Insert a right to suspend after notice if undisputed sums remain unpaid."),
    Protection("termination_payment_unclear", "termination", "medium",
               (r"(?:upon|on|following) terminat\w* .*(?:pay|paid|payment)", r"payment on terminat"),
               "No provision was identified for payment on termination.",
               "Specify payment for work done, demobilisation, and committed costs on any termination.",
               only_if=(r"terminat",)),
    Protection("insurance_coverage_gap", "insurance", "medium",
               (r"insurance", r"insured"),
               "No insurance provisions were identified, so neither party's cover obligations are defined.",
               "Insert insurance requirements aligned to the liability regime."),
    Protection("dispute_resolution_unfavourable", "contractual", "medium",
               (r"arbitrat", r"courts", r"dispute", r"mediation", r"expert determination"),
               "No dispute resolution clause was identified.", "Insert tiered dispute resolution ending in arbitration or courts."),
    Protection("governing_law_unfavourable", "contractual", "medium",
               (r"governed by", r"governing law", r"laws of"),
               "No governing law was identified, which leaves the meaning of key terms uncertain.", "State the governing law."),
    Protection("regulatory_compliance_burden", "compliance", "low",
               (r"change in (?:law|legislation)", r"change of law"),
               "No change-in-law protection was identified. New legislation or tax changes after bid date fall on the contractor.",
               "Insert change-in-law relief for cost and time."),
    Protection("price_escalation_unprotected", "commercial", "low",
               (r"escalat", r"index", r"price (?:adjustment|review)", r"rates? review", r"firm and fixed"),
               "Price adjustment is not addressed. On a long contract, cost increases are absorbed by the contractor.",
               "Agree indexation or a price review after a fixed period.",
               only_if=(r"(?:two|three|four|five|2|3|4|5) \(?\d?\)? ?years", r"(?:24|36|48|60) months")),
    Protection("confidentiality_obligation", "contractual", "low",
               (r"confidential", r"non-disclosure"),
               "No confidentiality clause was identified to protect the contractor's pricing and methods.",
               "Insert mutual confidentiality."),
    Protection("ip_rights_transfer", "contractual", "low",
               (r"intellectual property", r"\bipr?\b", r"background"),
               "Intellectual property is not addressed, so ownership of deliverables and know-how is uncertain.",
               "Insert IP provisions preserving the contractor's background IP."),
    Protection("defects_liability_exposure", "performance", "low",
               (r"warrant", r"defect", r"guarantee period"),
               "No warranty or defects clause was identified. Liability for defects then defaults to the general law, often for longer than a contractual period.",
               "Insert a defined defects period with an exclusive remedy."),
)
