"""clauserisk module: contracts, clauses, risk findings, cross-links, comparisons, license modules

Revision ID: 0bf5aa0c8c47
Revises: 12f91f9f4dd0
Create Date: 2026-09-21 23:37:10.483187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bf5aa0c8c47'
down_revision: Union[str, None] = '12f91f9f4dd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contracts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('created_by_user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('contract_type', sa.Enum('COMMERCIAL', 'EPC', 'OIL_AND_GAS', 'ENGINEERING', 'CONSTRUCTION', 'SERVICES', 'OTHER', name='contracttype', native_enum=False, length=20), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'UNDER_REVIEW', 'ACTIVE', 'SUPERSEDED', 'ARCHIVED', name='contractstatus', native_enum=False, length=20), nullable=False),
    sa.Column('counterparty_name', sa.String(length=255), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contracts_project_id'), 'contracts', ['project_id'], unique=False)
    op.create_table('contract_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('contract_id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('uploaded_by_user_id', sa.String(length=36), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('version_label', sa.String(length=100), nullable=False),
    sa.Column('analysis_status', sa.Enum('NOT_STARTED', 'PROCESSING', 'COMPLETED', 'FAILED', name='contractanalysisstatus', native_enum=False, length=20), nullable=False),
    sa.Column('analysis_error', sa.Text(), nullable=True),
    sa.Column('analysis_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('analysis_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contract_versions_contract_id'), 'contract_versions', ['contract_id'], unique=False)
    op.create_table('clauses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('contract_version_id', sa.String(length=36), nullable=False),
    sa.Column('clause_number', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('page_start', sa.Integer(), nullable=False),
    sa.Column('page_end', sa.Integer(), nullable=False),
    sa.Column('sequence_index', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('subcategory', sa.String(length=100), nullable=True),
    sa.Column('referenced_clauses', sa.Text(), nullable=False),
    sa.Column('extracted_obligations', sa.Text(), nullable=False),
    sa.Column('extracted_rights', sa.Text(), nullable=False),
    sa.Column('extracted_conditions', sa.Text(), nullable=False),
    sa.Column('extracted_exceptions', sa.Text(), nullable=False),
    sa.Column('extracted_amounts', sa.Text(), nullable=False),
    sa.Column('extracted_dates', sa.Text(), nullable=False),
    sa.Column('extracted_percentages', sa.Text(), nullable=False),
    sa.Column('extracted_time_periods', sa.Text(), nullable=False),
    sa.Column('source_confidence', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='sourceconfidence', native_enum=False, length=10), nullable=True),
    sa.Column('extraction_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contract_version_id'], ['contract_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clauses_contract_version_id'), 'clauses', ['contract_version_id'], unique=False)
    op.create_table('contract_comparisons',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('contract_id', sa.String(length=36), nullable=False),
    sa.Column('base_version_id', sa.String(length=36), nullable=False),
    sa.Column('compared_version_id', sa.String(length=36), nullable=False),
    sa.Column('created_by_user_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['base_version_id'], ['contract_versions.id'], ),
    sa.ForeignKeyConstraint(['compared_version_id'], ['contract_versions.id'], ),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contract_comparisons_contract_id'), 'contract_comparisons', ['contract_id'], unique=False)
    op.create_table('contract_changes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('comparison_id', sa.String(length=36), nullable=False),
    sa.Column('change_type', sa.Enum('ADDED', 'DELETED', 'MODIFIED', name='changetype', native_enum=False, length=20), nullable=False),
    sa.Column('clause_number', sa.String(length=50), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('base_clause_id', sa.String(length=36), nullable=True),
    sa.Column('compared_clause_id', sa.String(length=36), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('materiality', sa.Enum('MATERIAL', 'MINOR', name='materiality', native_enum=False, length=10), nullable=False),
    sa.Column('financial_delta', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['base_clause_id'], ['clauses.id'], ),
    sa.ForeignKeyConstraint(['compared_clause_id'], ['clauses.id'], ),
    sa.ForeignKeyConstraint(['comparison_id'], ['contract_comparisons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contract_changes_comparison_id'), 'contract_changes', ['comparison_id'], unique=False)
    op.create_table('cross_clause_links',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('contract_version_id', sa.String(length=36), nullable=False),
    sa.Column('clause_a_id', sa.String(length=36), nullable=False),
    sa.Column('clause_b_id', sa.String(length=36), nullable=False),
    sa.Column('relationship_type', sa.String(length=100), nullable=False),
    sa.Column('basis', sa.String(length=30), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['clause_a_id'], ['clauses.id'], ),
    sa.ForeignKeyConstraint(['clause_b_id'], ['clauses.id'], ),
    sa.ForeignKeyConstraint(['contract_version_id'], ['contract_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cross_clause_links_contract_version_id'), 'cross_clause_links', ['contract_version_id'], unique=False)
    op.create_table('risk_findings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('contract_version_id', sa.String(length=36), nullable=False),
    sa.Column('clause_id', sa.String(length=36), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('risk_type', sa.String(length=255), nullable=False),
    sa.Column('severity', sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', 'INFORMATIONAL', name='riskseverity', native_enum=False, length=20), nullable=False),
    sa.Column('risk_description', sa.Text(), nullable=False),
    sa.Column('contractual_effect', sa.Text(), nullable=True),
    sa.Column('potential_exposure', sa.Text(), nullable=True),
    sa.Column('trigger', sa.Text(), nullable=True),
    sa.Column('affected_party', sa.Enum('CONTRACTOR', 'CLIENT', 'BOTH', 'THIRD_PARTY', 'UNCLEAR', name='affectedparty', native_enum=False, length=20), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=False),
    sa.Column('related_clauses', sa.Text(), nullable=False),
    sa.Column('uncertainty', sa.Enum('EXPLICIT', 'NOT_APPLICABLE', 'NOT_FOUND', 'AMBIGUOUS', 'CONFLICTING', 'REQUIRES_REVIEW', name='riskuncertainty', native_enum=False, length=20), nullable=False),
    sa.Column('recommended_review_action', sa.Text(), nullable=True),
    sa.Column('risk_factors', sa.Text(), nullable=False),
    sa.Column('computed_score', sa.Float(), nullable=False),
    sa.Column('reviewer_status', sa.Enum('UNREVIEWED', 'ACCEPTED', 'REJECTED', 'MARKED_FOR_NEGOTIATION', 'REVIEWED', name='findingreviewerstatus', native_enum=False, length=30), nullable=False),
    sa.Column('assigned_to_user_id', sa.String(length=36), nullable=True),
    sa.Column('ai_provider', sa.String(length=50), nullable=True),
    sa.Column('prompt_version', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['clause_id'], ['clauses.id'], ),
    sa.ForeignKeyConstraint(['contract_version_id'], ['contract_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_findings_clause_id'), 'risk_findings', ['clause_id'], unique=False)
    op.create_index(op.f('ix_risk_findings_contract_version_id'), 'risk_findings', ['contract_version_id'], unique=False)
    op.add_column(
        'license_accounts',
        sa.Column('monthly_contract_limit', sa.Integer(), nullable=False, server_default='10'),
    )
    op.add_column(
        'license_accounts',
        sa.Column('monthly_clause_analysis_limit', sa.Integer(), nullable=False, server_default='10'),
    )
    op.add_column(
        'license_accounts',
        sa.Column(
            'enabled_modules',
            sa.String(length=200),
            nullable=False,
            server_default='["tenderguard", "clauserisk"]',
        ),
    )
    op.add_column('review_actions', sa.Column('risk_finding_id', sa.String(length=36), nullable=True))
    op.alter_column('review_actions', 'requirement_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.create_index(op.f('ix_review_actions_risk_finding_id'), 'review_actions', ['risk_finding_id'], unique=False)
    op.create_foreign_key(None, 'review_actions', 'risk_findings', ['risk_finding_id'], ['id'])
    # ### end Alembic commands ###

    # Not autogenerated: alembic's default autogenerate doesn't diff
    # CheckConstraint additions. Added by hand to match
    # app/models/review_action.py's __table_args__.
    op.create_check_constraint(
        "ck_review_action_exactly_one_target",
        "review_actions",
        "(requirement_id IS NOT NULL) != (risk_finding_id IS NOT NULL)",
    )


def downgrade() -> None:
    op.drop_constraint("ck_review_action_exactly_one_target", "review_actions", type_="check")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'review_actions', type_='foreignkey')
    op.drop_index(op.f('ix_review_actions_risk_finding_id'), table_name='review_actions')
    op.alter_column('review_actions', 'requirement_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.drop_column('review_actions', 'risk_finding_id')
    op.drop_column('license_accounts', 'enabled_modules')
    op.drop_column('license_accounts', 'monthly_clause_analysis_limit')
    op.drop_column('license_accounts', 'monthly_contract_limit')
    op.drop_index(op.f('ix_risk_findings_contract_version_id'), table_name='risk_findings')
    op.drop_index(op.f('ix_risk_findings_clause_id'), table_name='risk_findings')
    op.drop_table('risk_findings')
    op.drop_index(op.f('ix_cross_clause_links_contract_version_id'), table_name='cross_clause_links')
    op.drop_table('cross_clause_links')
    op.drop_index(op.f('ix_contract_changes_comparison_id'), table_name='contract_changes')
    op.drop_table('contract_changes')
    op.drop_index(op.f('ix_contract_comparisons_contract_id'), table_name='contract_comparisons')
    op.drop_table('contract_comparisons')
    op.drop_index(op.f('ix_clauses_contract_version_id'), table_name='clauses')
    op.drop_table('clauses')
    op.drop_index(op.f('ix_contract_versions_contract_id'), table_name='contract_versions')
    op.drop_table('contract_versions')
    op.drop_index(op.f('ix_contracts_project_id'), table_name='contracts')
    op.drop_table('contracts')
    # ### end Alembic commands ###
