"""add project demo flag and analysis status tracking

Revision ID: 12f91f9f4dd0
Revises: bf8c569512bf
Create Date: 2026-09-21 22:21:55.739723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12f91f9f4dd0'
down_revision: Union[str, None] = 'bf8c569512bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'projects',
        sa.Column('is_demo', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.add_column(
        'projects',
        sa.Column(
            'analysis_status',
            sa.Enum('NOT_STARTED', 'PROCESSING', 'COMPLETED', 'FAILED', name='analysisstatus', native_enum=False, length=20),
            nullable=False,
            server_default='NOT_STARTED',
        ),
    )
    op.add_column('projects', sa.Column('analysis_error', sa.Text(), nullable=True))
    op.add_column('projects', sa.Column('analysis_started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('projects', sa.Column('analysis_completed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'analysis_completed_at')
    op.drop_column('projects', 'analysis_started_at')
    op.drop_column('projects', 'analysis_error')
    op.drop_column('projects', 'analysis_status')
    op.drop_column('projects', 'is_demo')
    # ### end Alembic commands ###
