"""contract version analysis progress

Revision ID: 634826f7813b
Revises: 0bf5aa0c8c47
Create Date: 2026-09-22 15:31:03.941120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '634826f7813b'
down_revision: Union[str, None] = '0bf5aa0c8c47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "contract_versions", sa.Column("analysis_stage", sa.String(length=40), nullable=True)
    )
    # server_default is required here, not optional: these are NOT NULL and
    # the table already has rows from versions analysed before progress
    # tracking existed.
    op.add_column(
        "contract_versions",
        sa.Column(
            "analysis_progress_current", sa.Integer(), nullable=False, server_default="0"
        ),
    )
    op.add_column(
        "contract_versions",
        sa.Column("analysis_progress_total", sa.Integer(), nullable=False, server_default="0"),
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contract_versions', 'analysis_progress_total')
    op.drop_column('contract_versions', 'analysis_progress_current')
    op.drop_column('contract_versions', 'analysis_stage')
    # ### end Alembic commands ###
