"""documents, requirements, evidence, assessments, review actions, licensing

Revision ID: bf8c569512bf
Revises: a0f7244d45dc
Create Date: 2026-09-21 22:05:22.529704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf8c569512bf'
down_revision: Union[str, None] = 'a0f7244d45dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('license_accounts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('plan', sa.Enum('DEMO', 'TRIAL', 'PROFESSIONAL', 'ENTERPRISE', name='licenseplan', native_enum=False, length=20), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'EXPIRED', 'SUSPENDED', name='licensestatus', native_enum=False, length=20), nullable=False),
    sa.Column('seat_limit', sa.Integer(), nullable=False),
    sa.Column('project_limit', sa.Integer(), nullable=False),
    sa.Column('monthly_document_limit', sa.Integer(), nullable=False),
    sa.Column('monthly_analysis_limit', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id')
    )
    op.create_table('usage_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usage_events_organization_id'), 'usage_events', ['organization_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('uploaded_by_user_id', sa.String(length=36), nullable=False),
    sa.Column('document_type', sa.Enum('TENDER', 'BID', 'SUPPORTING', 'REFERENCE', name='documenttype', native_enum=False, length=20), nullable=False),
    sa.Column('original_filename', sa.String(length=512), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('storage_path', sa.String(length=1024), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('extraction_status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='extractionstatus', native_enum=False, length=20), nullable=False),
    sa.Column('extraction_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_project_id'), 'documents', ['project_id'], unique=False)
    op.create_table('document_pages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('char_count', sa.Integer(), nullable=False),
    sa.Column('extraction_method', sa.String(length=20), nullable=False),
    sa.Column('low_text_warning', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_pages_document_id'), 'document_pages', ['document_id'], unique=False)
    op.create_table('requirements',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('source_document_id', sa.String(length=36), nullable=False),
    sa.Column('source_page', sa.Integer(), nullable=False),
    sa.Column('source_clause', sa.String(length=255), nullable=True),
    sa.Column('source_excerpt', sa.Text(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('normalized_requirement', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('mandatory_status', sa.Enum('MANDATORY', 'CONDITIONAL', 'INDICATIVE', 'UNCLEAR', name='mandatorystatus', native_enum=False, length=20), nullable=False),
    sa.Column('conditions', sa.Text(), nullable=True),
    sa.Column('required_evidence', sa.Text(), nullable=True),
    sa.Column('extraction_uncertain', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['source_document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_requirements_project_id'), 'requirements', ['project_id'], unique=False)
    op.create_table('assessments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('requirement_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('NOT_ASSESSED', 'COMPLIANT_LOOKING', 'PARTIALLY_ADDRESSED', 'EVIDENCE_NOT_FOUND', 'POTENTIAL_NON_COMPLIANCE', 'NOT_APPLICABLE_PENDING_VERIFICATION', 'HUMAN_VERIFIED', 'HUMAN_REJECTED', name='assessmentstatus', native_enum=False, length=40), nullable=False),
    sa.Column('evidence_quality', sa.Enum('STRONG', 'ADEQUATE', 'INSUFFICIENT', 'NONE', 'UNKNOWN', name='evidencequality', native_enum=False, length=20), nullable=False),
    sa.Column('assessment_confidence', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='assessmentconfidence', native_enum=False, length=10), nullable=False),
    sa.Column('priority', sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', 'INFORMATIONAL', name='priority', native_enum=False, length=20), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('missing_information', sa.Text(), nullable=True),
    sa.Column('requires_human_review', sa.Boolean(), nullable=False),
    sa.Column('ai_provider', sa.String(length=50), nullable=True),
    sa.Column('prompt_version', sa.String(length=50), nullable=True),
    sa.Column('reviewer_status', sa.String(length=30), nullable=False),
    sa.Column('reviewer_user_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], ),
    sa.ForeignKeyConstraint(['reviewer_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('requirement_id')
    )
    op.create_table('evidence_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('requirement_id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('excerpt', sa.Text(), nullable=False),
    sa.Column('retrieval_method', sa.String(length=50), nullable=False),
    sa.Column('evidence_type', sa.String(length=100), nullable=True),
    sa.Column('relevance_note', sa.Text(), nullable=True),
    sa.Column('potential_conflict', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_records_requirement_id'), 'evidence_records', ['requirement_id'], unique=False)
    op.create_table('review_actions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('requirement_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('action_type', sa.String(length=30), nullable=False),
    sa.Column('previous_status', sa.String(length=50), nullable=True),
    sa.Column('new_status', sa.String(length=50), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_actions_requirement_id'), 'review_actions', ['requirement_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_actions_requirement_id'), table_name='review_actions')
    op.drop_table('review_actions')
    op.drop_index(op.f('ix_evidence_records_requirement_id'), table_name='evidence_records')
    op.drop_table('evidence_records')
    op.drop_table('assessments')
    op.drop_index(op.f('ix_requirements_project_id'), table_name='requirements')
    op.drop_table('requirements')
    op.drop_index(op.f('ix_document_pages_document_id'), table_name='document_pages')
    op.drop_table('document_pages')
    op.drop_index(op.f('ix_documents_project_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_usage_events_organization_id'), table_name='usage_events')
    op.drop_table('usage_events')
    op.drop_table('license_accounts')
    # ### end Alembic commands ###
